# openRigOS Board: Generic x86_64
ARCH=x86_64
DEBIAN_ARCH=amd64
DEBIAN_SUITE=bookworm
BOOTLOADER=grub-efi
IMAGE_TYPE=iso
QEMU_ARCH=x86_64

KERNEL_PACKAGE=linux-image-amd64
KERNEL_HEADERS=linux-headers-amd64

EXTRA_REPOS=""
EXTRA_REPO_KEY=""
FIRMWARE_PACKAGES="firmware-linux firmware-linux-nonfree"

GOARCH=amd64
