country=US
ctrl_interface=DIR=/var/run/wpa_supplicant GROUP=netdev
update_config=1

# Add your WiFi networks below.
# You can add multiple network blocks.
#
# network={
#     ssid="YourNetworkName"
#     psk="YourPassword"
# }
