# openRigOS Board: Raspberry Pi 5
# SoC: BCM2712, Cortex-A76, up to 8GB RAM
ARCH=arm64
DEBIAN_ARCH=arm64
DEBIAN_SUITE=bookworm
BOOTLOADER=rpi-firmware
IMAGE_TYPE=img
IMAGE_SIZE=4G
QEMU_ARCH=aarch64

KERNEL_PACKAGE=raspberrypi-kernel
KERNEL_HEADERS=raspberrypi-kernel-headers

DTB=bcm2712-rpi-5-b.dtb

EXTRA_REPOS="deb http://archive.raspberrypi.com/debian/ bookworm main"
EXTRA_REPO_KEY="https://archive.raspberrypi.com/debian/raspberrypi.gpg.key"

FIRMWARE_PACKAGES="raspberrypi-bootloader firmware-brcm80211 pi-bluetooth"

GOARCH=arm64
